Loaded dependency [numpy/1.23.3-python-3.10.7-openblas-0.3.21]: openblas/0.3.21
Loaded dependency [python3/3.10.7]: gcc/11.3.0-binutils-2.38
Loaded dependency [numpy/1.23.3-python-3.10.7-openblas-0.3.21]: python3/3.10.7
Loaded dependency [pandas/1.4.4-python-3.10.7]: numpy/1.23.3-python-3.10.7-openblas-0.3.21
Loaded module: pandas/1.4.4-python-3.10.7

Loading pandas/1.4.4-python-3.10.7
  Loading requirement: openblas/0.3.21 gcc/11.3.0-binutils-2.38 python3/3.10.7
    numpy/1.23.3-python-3.10.7-openblas-0.3.21
Loaded module: matplotlib/3.6.0-numpy-1.23.3-python-3.10.7
Loaded module: cuda/11.6
Global seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/zhome/56/e/155505/Desktop/DeepLearningProject/diffwave/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py:48: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
Traceback (most recent call last):
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_main.py", line 62, in <module>
    main()
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_main.py", line 58, in main
    fit_model(model, params, experiment_name, global_seed, max_epochs)
  File "/zhome/56/e/155505/Desktop/DeepLearningProject/experiment_helpers.py", line 130, in fit_model
    return data.val_set.timer, data.train_set.timer, timer_experiment_helpers, model.timer
AttributeError: 'SpeechDataModule' object has no attribute 'val_set'
